//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfTest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cesEntities : DbContext
    {
        public cesEntities()
            : base("name=cesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<job_demand> job_demand { get; set; }
        public DbSet<job_fields> job_fields { get; set; }
        public DbSet<job_requirements> job_requirements { get; set; }
        public DbSet<program> programs { get; set; }
        public DbSet<province> provinces { get; set; }
        public DbSet<university> universities { get; set; }
        public DbSet<university_programs> university_programs { get; set; }
        public DbSet<username> usernames { get; set; }
    }
}
