//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class job_demand
    {
        public long id { get; set; }
        public long job_field_id { get; set; }
        public long province_id { get; set; }
        public Nullable<long> demand { get; set; }
        public Nullable<long> forecast_year { get; set; }
        public long program_id { get; set; }
    
        public virtual job_fields job_fields { get; set; }
        public virtual program program { get; set; }
        public virtual province province { get; set; }
    }
}
