//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class university
    {
        public university()
        {
            this.university_programs = new HashSet<university_programs>();
        }
    
        public long id { get; set; }
        public int province_id { get; set; }
        public string name { get; set; }
    
        public virtual province province { get; set; }
        public virtual ICollection<university_programs> university_programs { get; set; }
    }
}
