//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class university_programs
    {
        public long id { get; set; }
        public long university_id { get; set; }
        public long program_id { get; set; }
        public long current_enrollment { get; set; }
        public long available_seats { get; set; }
    
        public virtual program program { get; set; }
        public virtual university university { get; set; }
    }
}
